# Generated by Django 6.0.4 on 2026-04-24 22:25

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [] # empty list for now

    operations = [
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_country", models.CharField(max_length=64)),
                ("destination_country", models.CharField(max_length=64)),
                ("number_of_nights", models.IntegerField()),
                ("price", models.IntegerField()),
            ],
        ),
    ]
